### ISSUE TITLE
Unexpected error while connecting to serial port

### ISSUE THREAD

**Issue by bwente** [OctoPrint/OctoPrint-MonopriceDeltaCompat#1]
Fresh install. 
OctoPrint version : 1.3.4
OctoPi version    : 0.14.0

Monoprice Mini Delta.

Serial Port (set to auto)
Baudrate (set to auto)
`Unexpected error while connecting to serial port: AUTO AttributeError: ''MachineCom' object has no attribute '_detect_port'' @ comm.py:_openSerial:1754 (hook monopricedeltacompat)`

Manually set...

```
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0xad251bb0, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=True, rtscts=True, dsrdtr=True), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: N0 M110 N0*125
There was a timeout while trying to connect to the printer
Changing monitoring state from 'Connecting' to 'Offline'
Connection closed, closing down monitor
```

**Comment by idcrook** [comment]
I too can report this issue.  It occurs when setting [Serial Port] to [AUTO]. Explicitly choosing the port, e.g. `/dev/ttyACM0`, avoids this error.

**Comment by bwente** [comment]
What baud ? I still can't connect wth manually setting the port. However the "connect", "disconnect", "connect" dance does work.

**Comment by idcrook** [comment]
I also need to still do the conn/disconn/conn sequencing.

**Comment by foosel** [comment]
The goal of this plugin is avoiding that dance ;) But let's tackle this issue first. I assumed the presence of a method that was added in OctoPrint 1.3.5, which is currently only available as release candidate. I've adjusted the plugin to be able to handle that.

What I've also done is ONLY set rtscts to True instead of all of those flow control parameters. As far as I understand it, hardware flow control through rtscts appears to be what makes stuff work with e.g. S3D, so let's try that to see if having only that present also avoids that stupid reconnect dance.

Please try uninstalling and reinstalling the plugin (apparently something in the update configuration is still broken). Absolutely no guarantees that that will make the connection work without issues, it might even make stuff connect less. Due to lack of (and space for) that printer I'm pretty much flying blind here and am just poking at things in the hopes one of you might come back with "hah, now it works all the time" ;)
